/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        base: 'rgb(var(--n-base) / <alpha-value>)',
        surface: 'rgb(var(--n-surface) / <alpha-value>)',
        elevated: 'rgb(var(--n-elevated) / <alpha-value>)',
        hover: 'rgb(var(--n-hover) / <alpha-value>)',
        border: 'rgb(var(--n-border) / <alpha-value>)',
        'border-light': 'rgb(var(--n-border-light) / <alpha-value>)',
        zebra: 'rgb(var(--n-elevated) / <alpha-value>)',

        primary: 'rgb(var(--n-primary) / <alpha-value>)',
        secondary: 'rgb(var(--n-secondary) / <alpha-value>)',
        tertiary: 'rgb(var(--n-tertiary) / <alpha-value>)',

        accent: {
          DEFAULT: 'rgb(var(--a-accent) / <alpha-value>)',
          hover: 'rgb(var(--a-accent-hover) / <alpha-value>)',
          muted: 'rgb(var(--a-accent-muted) / <alpha-value>)',
          dim: 'rgb(var(--a-accent-dim) / <alpha-value>)',
        },

        'accent-secondary': {
          DEFAULT: 'rgb(var(--a-accent-secondary) / <alpha-value>)',
          hover: 'rgb(var(--a-accent-secondary-hover) / <alpha-value>)',
          muted: 'rgb(var(--a-accent-secondary-muted) / <alpha-value>)',
          dim: 'rgb(var(--a-accent-secondary-dim) / <alpha-value>)',
        },

        success: 'rgb(var(--a-success) / <alpha-value>)',
        'success-muted': 'rgb(var(--a-success-muted) / <alpha-value>)',
        warning: 'rgb(var(--a-warning) / <alpha-value>)',
        'warning-muted': 'rgb(var(--a-warning-muted) / <alpha-value>)',
        error: 'rgb(var(--a-error) / <alpha-value>)',
        'error-muted': 'rgb(var(--a-error-muted) / <alpha-value>)',
        info: 'rgb(var(--a-info) / <alpha-value>)',

        health: {
          excellent: 'rgb(var(--s-health-excellent) / <alpha-value>)',
          good: 'rgb(var(--s-health-good) / <alpha-value>)',
          moderate: 'rgb(var(--s-health-moderate) / <alpha-value>)',
          poor: 'rgb(var(--s-health-poor) / <alpha-value>)',
          'excellent-light': 'rgb(var(--s-health-excellent-light) / <alpha-value>)',
          'good-light': 'rgb(var(--s-health-good-light) / <alpha-value>)',
          'moderate-light': 'rgb(var(--s-health-moderate-light) / <alpha-value>)',
          'poor-light': 'rgb(var(--s-health-poor-light) / <alpha-value>)',
        },

        trust: {
          high: 'rgb(var(--s-health-excellent) / <alpha-value>)',
          medium: 'rgb(var(--s-health-moderate) / <alpha-value>)',
          low: 'rgb(var(--n-tertiary) / <alpha-value>)',
        },

        metric: {
          cardiac:     'rgb(var(--s-metric-cardiac) / <alpha-value>)',
          sleep:       'rgb(var(--s-metric-sleep) / <alpha-value>)',
          respiratory: 'rgb(var(--s-metric-respiratory) / <alpha-value>)',
          activity:    'rgb(var(--s-metric-activity) / <alpha-value>)',
          body:        'rgb(var(--s-metric-body) / <alpha-value>)',
          clinical:    'rgb(var(--s-metric-clinical) / <alpha-value>)',
          'cardiac-light':     'rgb(var(--s-metric-cardiac-light) / <alpha-value>)',
          'sleep-light':       'rgb(var(--s-metric-sleep-light) / <alpha-value>)',
          'respiratory-light': 'rgb(var(--s-metric-respiratory-light) / <alpha-value>)',
          'activity-light':    'rgb(var(--s-metric-activity-light) / <alpha-value>)',
          'body-light':        'rgb(var(--s-metric-body-light) / <alpha-value>)',
          'clinical-light':    'rgb(var(--s-metric-clinical-light) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '0.9375rem' }],
        xs: ['0.75rem', { lineHeight: '1.0625rem' }],
        sm: ['0.8125rem', { lineHeight: '1.125rem' }],
        base: ['0.875rem', { lineHeight: '1.25rem' }],
        lg: ['0.9375rem', { lineHeight: '1.3125rem' }],
        xl: ['1.0625rem', { lineHeight: '1.4375rem' }],
        '2xl': ['1.3125rem', { lineHeight: '1.6875rem' }],
        '3xl': ['1.5625rem', { lineHeight: '1.9375rem' }],
        '4xl': ['2.125rem', { lineHeight: '2.375rem' }],
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '8px',
        md: '10px',
        lg: '12px',
        xl: '16px',
      },
      boxShadow: {
        none: 'none',
        sm: '0 1px 2px rgb(var(--n-shadow) / 0.04)',
        DEFAULT: '0 1px 3px rgb(var(--n-shadow) / 0.06), 0 1px 2px rgb(var(--n-shadow) / 0.04)',
        md: '0 4px 6px rgb(var(--n-shadow) / 0.06), 0 2px 4px rgb(var(--n-shadow) / 0.04)',
        lg: '0 10px 15px rgb(var(--n-shadow) / 0.06), 0 4px 6px rgb(var(--n-shadow) / 0.04)',
        'accent-sm': '0 0 0 1px rgb(var(--a-accent) / 0.12), 0 2px 8px rgb(var(--a-accent) / 0.10)',
        'accent-md': '0 0 0 1px rgb(var(--a-accent) / 0.18), 0 4px 16px rgb(var(--a-accent) / 0.14)',
      },
      animation: {
        'fade-in': 'fadeIn 150ms ease-out',
        'slide-in': 'slideIn 150ms ease-out',
        'flow-pulse': 'flowPulse 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'node-appear': 'nodeAppear 400ms ease-out forwards',
        'count-up': 'countUp 300ms ease-out',
        'hash-reveal': 'hashReveal 600ms steps(20) forwards',
        'proof-step': 'proofStep 500ms ease-out forwards',
        'slide-up': 'slideUp 200ms ease-out',
        // ZK Bridge animation keyframes
        'zk-data-bounce': 'zkDataBounce 6s ease-in-out infinite',
        'zk-receipt-glide': 'zkReceiptGlide 6s ease-in-out infinite',
        'zk-shield-pulse': 'zkShieldPulse 6s ease-in-out infinite',
        'zk-partner-confirm': 'zkPartnerConfirm 6s ease-in-out infinite',
        'zk-hash-appear': 'zkHashAppear 6s ease-in-out infinite',
      },
      keyframes: {
        zkDataBounce: {
          '0%, 100%': { transform: 'translateX(0)', opacity: '1' },
          '12%': { transform: 'translateX(60px)', opacity: '1' },
          '18%': { transform: 'translateX(30px) scale(0.9)', opacity: '0.7' },
          '24%': { transform: 'translateX(0)', opacity: '1' },
          '25%, 100%': { transform: 'translateX(0)', opacity: '1' },
        },
        zkReceiptGlide: {
          '0%, 30%': { transform: 'translateX(0)', opacity: '0' },
          '35%': { transform: 'translateX(0)', opacity: '1' },
          '60%': { transform: 'translateX(110px)', opacity: '1' },
          '65%': { transform: 'translateX(110px)', opacity: '1' },
          '75%, 100%': { transform: 'translateX(110px)', opacity: '0' },
        },
        zkHashAppear: {
          '0%, 32%': { opacity: '0', transform: 'translateY(4px)' },
          '38%': { opacity: '1', transform: 'translateY(0)' },
          '70%': { opacity: '1', transform: 'translateY(0)' },
          '78%, 100%': { opacity: '0', transform: 'translateY(4px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        flowPulse: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        nodeAppear: {
          '0%': { opacity: '0', transform: 'scale(0.85)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        countUp: {
          '0%': { opacity: '0.5', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        hashReveal: {
          '0%': { maxWidth: '0', opacity: '0' },
          '100%': { maxWidth: '100%', opacity: '1' },
        },
        proofStep: {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
