// ===========================================================================
// Model metadata — "models = assumption sets" (Assumptions Studio brief §1).
//
// A Model is a named assumption set plus governance/provenance metadata. The
// engine resolves the active Model per request (resolveActiveModel) and every
// number in the app is computed against the selected Model. This file holds the
// metadata types only — the assumption *payload* shape lives in the engine's
// VersionedAssumptionSet, which a Model wraps.
// ===========================================================================

// How a Model's numbers were arrived at.
//  - evidence:           published literature / regulator stats (the "floor")
//  - forward:            forward / upside calibration, explicitly labelled
//  - ai:                 generated by an AI pass (exploration / stress-test)
//  - expert_calibrated:  an actuary-signed calibration (e.g. backtest-derived)
export type ModelBasis = "evidence" | "forward" | "ai" | "expert_calibrated";

// Sign-off state. A `signed` Model is a governed floor an actuary has named and
// dated; `draft` is still being worked.
export type ModelGovernanceStatus = "draft" | "signed";

// Where the Model sits in the floor/base/ceiling spread. Drives UI trust tone:
// `floor` renders normally; `ceiling` carries a "projected" label.
export type ModelConfidencePosture = "floor" | "base" | "ceiling";

// Who may see / select a Model. `internal_only` Models (e.g. the pure-AI Model 3)
// must never become the default for a buyer-facing session and are watermarked.
export type ModelVisibility = "buyer_facing" | "internal_only";

// Provenance of a single assumption value. Drives the confidence flag in Studio.
//  literature  🟢  — published source
//  proxy       🟡  — mapped from an analogous source
//  asserted    🟠  — expert assertion, no external source (review target)
//  ai_projected🔵  — proposed by an AI pass
export type ProvenanceType = "literature" | "proxy" | "asserted" | "ai_projected";

export const PROVENANCE_FLAG: Record<ProvenanceType, { glyph: string; label: string }> = {
  literature: { glyph: "🟢", label: "Literature" },
  proxy: { glyph: "🟡", label: "Proxy / analogy" },
  asserted: { glyph: "🟠", label: "Asserted (no source)" },
  ai_projected: { glyph: "🔵", label: "AI-projected" },
};

// Per-assumption provenance, attached to assumption rows in the Studio.
export interface AssumptionProvenance {
  provenanceType: ProvenanceType;
  sourceText?: string;
  // confidence interval / plausible range for the value, when known
  ci?: [number, number];
  lastEditedBy?: string;
  lastEditedAt?: string;
}

// The metadata envelope around an assumption set that makes it a Model.
export interface ModelMeta {
  id: string;
  name: string;
  basis: ModelBasis;
  governanceStatus: ModelGovernanceStatus;
  confidencePosture: ModelConfidencePosture;
  visibility: ModelVisibility;
  // Model 2's parent = Model 1, so the Studio can diff a fork against its floor.
  parentModelId?: string;
  version: string;
  owner?: string;
  signedBy?: string;
  signedAt?: string;
  // one-line description shown in the switcher
  summary?: string;
}

// A labelled adjustment a child Model (e.g. Model 2 forward) makes vs its parent.
// Every forward / ai_projected lever requires a rationale — no un-sourced edits.
export interface ModelAdjustment {
  // dotted path into the assumption set, e.g. "economic.claimsBridge.steps.attributionFactor"
  path: string;
  label: string;
  fromValue: number | string;
  toValue: number | string;
  rationale: string;
  provenanceType: ProvenanceType;
}

// A single logged change to an assumption (governance change log §5).
export interface ModelChangeLogEntry {
  id: string;
  modelId: string;
  path: string;
  label: string;
  fromValue: number | string;
  toValue: number | string;
  rationale: string;
  actor: string;
  at: string;
}

// What the /api/models list endpoint returns — metadata only, no heavy payload.
export interface ModelSummary extends ModelMeta {
  // true when this Model may be selected in the current (buyer/demo) context
  selectableInBuyerContext: boolean;
}

// Whether a Model is safe to surface as the active model in a buyer-facing
// session: it must be visible to buyers. (Governance gating — unsigned models
// are still selectable but render with a draft tone; internal_only never is.)
export function isBuyerSelectable(meta: ModelMeta): boolean {
  return meta.visibility === "buyer_facing";
}

// Trust tone for badges/labels derived from posture + governance.
export function modelTrustTone(meta: ModelMeta): "floor" | "projected" | "exploratory" {
  if (meta.visibility === "internal_only") return "exploratory";
  if (meta.confidencePosture === "ceiling" || meta.basis === "forward" || meta.basis === "ai") {
    return "projected";
  }
  return "floor";
}
